### ISSUE TITLE
What should be the criteria for students to be considered graduates?

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#5]
For the next edition of the Academy, we should have clear graduation criteria. 

This can include 

- Attendance level
- Completion of exercises 
- Completion of capstone 

We might, optionally, provide a grading system, to benefit students who outperform the rest.

**Comment by HugoDLopes** [comment]
My opinion, for regular grading:
- 100% attendance in LU
- 50% presence in hackathons
- Last hackathon mandatory with individual grading

**Comment by hershaw** [comment]
If we provide assignments that can be automatically graded then for the LUs we will have that. The other place that students can stand out is in the hackathons themselves which is a bit more tricky to assign credit for since most of them will be in teams...

Building on Hugo's ideas, I'll suggest the following (assuming assignments are graded)

- 80% average on LU assignments
- 75% presence in hackathons (allow them to miss 1 or 2)
- Pass all milestones on time for capstone project

**Comment by HugoDLopes** [comment]
We could have some personal notes we take during the hackathons regarding students that work a lot or wait for the work of others. This will be subjective but with enough amount of data, we might have a good estimation of the individual performance. We could even apply machine learning algorithms to the data we generate, right?

**Comment by echo66** [comment]
@HugoDLopes and @hershaw, are you guys referring to graduates or honor graduates? Or are we gonna deprecate the honor thing?

**Comment by HugoDLopes** [comment]
We could still have the honors, but I think it will come after the baseline graduate. And probably much easier to define, such as: all hackathons and great performance in the last one.
