### ISSUE TITLE
Deployment Hackathon Duration and Engagement

### ISSUE THREAD

**Issue by HugoDLopes** [LDSSA/instructors-forum#9]
Next edition should really take into account students feedback, but I'd like to add some points:
- The duration was very long which led to people start strong but then quit. We should try to find a way to keep people engaged.
- One idea: since the reports were not that great, the focus on the hackathon day could also be in writing the report.

**Comment by echo66** [comment]
We should compare Heroku and Google Cloud Platform in terms of ease of usage. Unlike Heroku, it doesn't have serious limitations like databases, file systems, etc and it is really easy to use (I'm learning all by myself through youtube videos).

**Comment by hershaw** [comment]
@echo66 that's a good point, the database limitations were a bit unfortunate. However everything else with Heroku was wonderfully easy... It's going to be difficult to beat that. Are you available to do some quick experimentation and see how difficult it might be?

@HugoDLopes yes it was a bit long and the fact that one month of it was in December made it worse. I basically added 3 weeks to the timeline to make it more doable for people because of the holiday which means that if we plan better we can chop at lest 3 weeks off of the total duration. The other reason it required so much time was because of the true observations coming in and wanting to give them a chance to re-train and deploy which required an extra week to be added. Basically, it could be done in two weeks without true outcomes and not being done during the holidays.

What do you think?

**Comment by HugoDLopes** [comment]
@hershaw I think less time is better. Or give two shot opportunities. One of our problems was the definition of the deadlines too close to the hackathon itself, but that won't happen on the next one.

**Comment by echo66** [comment]
@hershaw I will have to use it for a serious side project. This will make sure you will get some feedback on it from me.
